// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPzv_QQRlamp0AsHy9npjQFpgYe2xcGw',
    appId: '1:463075629322:web:5f5d9d0d47845ca4b142f3',
    messagingSenderId: '463075629322',
    projectId: 'minerapresilogin',
    authDomain: 'minerapresilogin.firebaseapp.com',
    storageBucket: 'minerapresilogin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9feAFdVAcQEj66HJwG0ekrYAPjjJYCkU',
    appId: '1:463075629322:android:c687bf33905d11fdb142f3',
    messagingSenderId: '463075629322',
    projectId: 'minerapresilogin',
    storageBucket: 'com.example.mineralogin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUP57qVNdE4ASz2Rnfm9p4eFzsRJ-3qU',
    appId: '1:463075629322:ios:3af83458961c98efb142f3',
    messagingSenderId: '463075629322',
    projectId: 'minerapresilogin',
    storageBucket: 'minerapresilogin.firebasestorage.app',
    iosBundleId: 'com.example.mineralogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPzv_QQRlamp0AsHy9npjQFpgYe2xcGw',
    appId: '1:463075629322:web:6d47dec3f9a3bac0b142f3',
    messagingSenderId: '463075629322',
    projectId: 'minerapresilogin',
    authDomain: 'minerapresilogin.firebaseapp.com',
    storageBucket: 'minerapresilogin.firebasestorage.app',
  );
}
